return {
	"folke/snacks.nvim",
	priority = 1000,
	lazy = false,
	opts = {
		styles = {
			terminal = {
				border = vim.o.winborder,
			},
		},
		bigfile = { enabled = false },
		bufdelete = { enabled = true },
		dashboard = {
			preset = {
				header = table.concat({
					" █████╗ ██████╗ ██████╗ ██╗ █████╗ ███╗   ██╗███╗   ██╗██╗ ██████╗",
					"██╔══██╗██╔══██╗██╔══██╗██║██╔══██╗████╗  ██║████╗  ██║██║██╔════╝",
					"███████║██║  ██║██████╔╝██║███████║██╔██╗ ██║██╔██╗ ██║██║██║     ",
					"██╔══██║██║  ██║██╔══██╗██║██╔══██║██║╚██╗██║██║╚██╗██║██║██║     ",
					"██║  ██║██████╔╝██║  ██║██║██║  ██║██║ ╚████║██║ ╚████║██║╚██████╗",
					"╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═══╝╚═╝ ╚═════╝",
				}, "\n"),
			},
			sections = {
				{ section = "header" },
				{ section = "keys", gap = 1, padding = 1 },
			},
		},
		dim = { enabled = false },
		explorer = { enabled = true },
		gitbrowse = { enabled = true },
		image = { enabled = true },
		indent = {
			enabled = true,
			animate = {
				enabled = false,
			},
		},
		input = { enabled = true },
		layout = { enabled = true },
		lazygit = { enabled = vim.fn.executable("lazygit") == 1 },
		notifier = { enabled = true },
		picker = { enabled = true },
		profiler = { enabled = true },
		quickfile = { enabled = true },
		rename = { enabled = true },
		scope = { enabled = true },
		statuscolumn = { enabled = true },
		terminal = { enabled = true },
		win = { enabled = true },
		words = { enabled = true },
	},
	keys = {
		-- Buffers
		{ "<Leader>c", function() Snacks.bufdelete.delete() end, desc = "Close buffer"},
		-- Find
		{ "<Leader>fP", function() Snacks.picker.pickers() end, desc = "Find pickers" },
		{ "<Leader>fT", function() Snacks.picker.todo_comments({ keywords = { "TODO", "FIX", "FIXME" } }) end, desc = "Find todos/fix/fixme" },
		{ "<Leader>fc", function() Snacks.picker.grep_word() end, desc = "Find word under cursor", mode = { "n", "x" } },
		{ "<Leader>ff", function() Snacks.picker.files() end, desc = "Find files" },
		{ "<Leader>fh", function() Snacks.picker.help() end, desc = "Find help" },
		{ "<Leader>fm", function() Snacks.picker.man() end, desc = "Find manuals" },
		{ "<Leader>fn", function() Snacks.picker.notifications() end, desc = "Find notifications" },
		{ "<Leader>fp", function() Snacks.picker.projects() end, desc = "Find projects" },
		{ "<Leader>fs", function() Snacks.picker.smart() end, desc = "Find Smart" },
		{ "<Leader>ft", function() Snacks.picker.todo_comments() end, desc = "Find todos" },
		{ "<Leader>fu", function() Snacks.picker.undo() end, desc = "Find undo history" },
		{ "<Leader>fw", function() Snacks.picker.grep() end, desc = "Find word" },
		-- Git
		{ "<Leader>gI", function() Snacks.picker.gh_issue({ state = "all" }) end, desc = "Github Issues (all)" },
		{ "<Leader>gP", function() Snacks.picker.gh_pr({ state = "all" }) end, desc = "Github Pull Requests (all)" },
		{ "<Leader>gb", function() Snacks.picker.git_branches() end, desc = "Git branches" },
		{ "<Leader>gd", function() Snacks.picker.git_diff() end, desc = "Git diff" },
		{ "<Leader>gf", function() Snacks.picker.git_files() end, desc = "Git find files" },
		{ "<Leader>gg", function() Snacks.lazygit.open() end, desc = "Lazygit" },
		{ "<Leader>gi", function() Snacks.picker.gh_issue() end, desc = "Github Issues (open)" },
		{ "<Leader>gl", function() Snacks.picker.git_log() end, desc = "Git log" },
		{ "<Leader>go", function() Snacks.gitbrowse.open() end, desc = "Git open" },
		{ "<Leader>gp", function() Snacks.picker.gh_pr() end, desc = "Github Pull Requests (open)" },
		{ "<Leader>gs", function() Snacks.picker.git_status() end, desc = "Git status" },
		{ "<Leader>gw", function() Snacks.picker.git_grep() end, desc = "Git find word" },
		-- Terminal
		{ "<Leader>tf", function() Snacks.terminal.toggle("bash") end, desc = "Toggle floating terminal" },
	},
}
